### ISSUE TITLE
Project goal

### ISSUE THREAD

**Issue by suhasghorp** [apssouza22/trading-system#11]
Hello, I was wondering why you decided to add Spring framework to the project. It adds a lot of bloat and is not really required here in my opinion.  None of the "high frequency" trading systems would ever have Spring boot in the mix. You should probably look into using Chronicle libraries, Eclipse collections etc.  Just my opinion. Thanks.

**Comment by apssouza22** [comment]
Spring is used just to expose a rest api, the core module is not using any framework. It should not impact on the engine performance 

Chronicle libraries can be a great performance improvement indeed. There are others initiatives as well to avoid threads(context switching) and gc, but I preferred to go with pure Java. Performance improvements should be always the last step in any system and always guided by metrics. 

Thanks for the suggestion anyway
